services:
  php-fpm:
    build:
      context: .
      dockerfile: infra/Dockerfile.php
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: infra/Dockerfile.nginx
      target: local
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - php-fpm

  node:
    build:
      context: .
      dockerfile: infra/Dockerfile.node
      target: local
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  composer_install:
    build:
      context: .
      dockerfile: infra/Dockerfile.php
    volumes:
      - ./backend:/var/www:delegated
    command: composer install -o

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: local
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:
