# https://taskfile.dev

version: '3'

tasks:
  up:
    desc: '開発環境の起動'
    cmds:
      - docker compose up --build --force-recreate
  down:
    desc: '開発環境の停止'
    cmds:
      - docker compose down --remove-orphans
  enter-php:
    desc: 'PHPコンテナに入る'
    deps: [ up ]
    cmds:
      - docker compose exec php-fpm bash
