# https://taskfile.dev

version: '3'

tasks:
  up:
    desc: '開発環境の起動'
    cmds:
      - mkdir -p frontend/node_modules
      - docker compose up -d --build --force-recreate
      - docker compose logs -f
  down:
    desc: '開発環境の停止'
    cmds:
      - docker compose down --remove-orphans
  enter-php:
    desc: 'PHPコンテナに入る'
    cmds:
      - docker compose exec php-fpm bash
  enter-node:
    desc: 'Node.jsコンテナに入る'
    cmds:
      - docker compose exec node bash
  migrate:
    desc: 'データベースのマイグレーションを実行'
    cmds:
      - docker compose exec php-fpm php artisan migrate --seed
  test:
    desc: 'ユニットテストを実行'
    cmds:
      - docker compose exec php-fpm php artisan test
  format:
    desc: 'コードのフォーマットとLintを実行'
    cmds:
      - docker compose exec node npm run lintfix
