FROM node:22-slim AS builder

WORKDIR /app

COPY ./frontend/package.json      ./package.json
COPY ./frontend/package-lock.json ./package-lock.json
RUN npm ci


FROM node:22-slim AS local

COPY --from=builder /app/node_modules /app/node_modules

WORKDIR /app

ENV HOST 0.0.0.0
CMD ["npm", "run", "dev"]

# TODO: production build
