name: Backend Tests (Laravel)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_sqlite, bcmath, dom, fileinfo, json, tokenizer, xml
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare environment (.env and testing DB)
        run: |
          cp .env.example .env
          mkdir -p database
          touch database/database.sqlite
          {
            echo "APP_ENV=testing"
            echo "DB_CONNECTION=sqlite"
            echo "DB_DATABASE=${GITHUB_WORKSPACE}/backend/database/database.sqlite"
          } >> .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Optimize Laravel bootstrap
        run: php artisan config:clear

      - name: Run Migrations
        env:
          APP_ENV: testing
        run: php artisan migrate --force --no-interaction

      - name: Run Unit Tests
        env:
          APP_ENV: testing
        run: php artisan test --no-interaction
